# Generated by Django 3.2.4 on 2021-06-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210630_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
