# Generated by Django 3.2.4 on 2021-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lesson_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание курса'),
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_members',
            field=models.CharField(blank=True, max_length=10, verbose_name='Размер группы'),
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.CharField(blank=True, max_length=20, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='category',
            name='tutor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Преподаватель'),
        ),
    ]
