# Generated by Django 3.2.4 on 2021-07-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210703_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_landing',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Лендинг курса'),
        ),
    ]
