# Generated by Django 3.2.6 on 2021-08-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210707_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_lesson_bots',
            field=models.CharField(default='nastrojka-bota/', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_lesson_ege',
            field=models.CharField(default='testovyj-ege/', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_lesson_python',
            field=models.CharField(default='tipy-dannyh/', max_length=50),
        ),
    ]
